language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5

install:
  - go get github.com/go-ozzo/ozzo-config
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go list -f '{{range .Imports}}{{.}} {{end}}' ./... | xargs go get -v
  - go list -f '{{range .TestImports}}{{.}} {{end}}' ./... | xargs go get -v

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
