// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package basegate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionImp struct {
	IP                   string            `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Network              string            `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
	UserId               string            `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	SessionId            string            `protobuf:"bytes,4,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	ServerId             string            `protobuf:"bytes,5,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	TraceId              string            `protobuf:"bytes,6,opt,name=TraceId,proto3" json:"TraceId,omitempty"`
	SpanId               string            `protobuf:"bytes,7,opt,name=SpanId,proto3" json:"SpanId,omitempty"`
	Settings             map[string]string `protobuf:"bytes,8,rep,name=Settings,proto3" json:"Settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Carrier              map[string]string `protobuf:"bytes,9,rep,name=Carrier,proto3" json:"Carrier,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Topic                string            `protobuf:"bytes,10,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SessionImp) Reset()         { *m = SessionImp{} }
func (m *SessionImp) String() string { return proto.CompactTextString(m) }
func (*SessionImp) ProtoMessage()    {}
func (*SessionImp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *SessionImp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionImp.Unmarshal(m, b)
}
func (m *SessionImp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionImp.Marshal(b, m, deterministic)
}
func (m *SessionImp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionImp.Merge(m, src)
}
func (m *SessionImp) XXX_Size() int {
	return xxx_messageInfo_SessionImp.Size(m)
}
func (m *SessionImp) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionImp.DiscardUnknown(m)
}

var xxx_messageInfo_SessionImp proto.InternalMessageInfo

func (m *SessionImp) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *SessionImp) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *SessionImp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SessionImp) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SessionImp) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *SessionImp) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *SessionImp) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *SessionImp) GetSettings() map[string]string {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *SessionImp) GetCarrier() map[string]string {
	if m != nil {
		return m.Carrier
	}
	return nil
}

func (m *SessionImp) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*SessionImp)(nil), "basegate.sessionImp")
	proto.RegisterMapType((map[string]string)(nil), "basegate.sessionImp.CarrierEntry")
	proto.RegisterMapType((map[string]string)(nil), "basegate.sessionImp.SettingsEntry")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14) }

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x62, 0xf3, 0x67, 0xb4, 0x22, 0x83, 0xc8, 0x12, 0x3c, 0xd4, 0x9e, 0x7a, 0xca,
	0x41, 0x2f, 0xd2, 0x82, 0x17, 0xf1, 0x90, 0x8b, 0x94, 0xa6, 0x3e, 0xc0, 0xb6, 0x19, 0x4a, 0xa8,
	0x66, 0xc3, 0xee, 0x5a, 0xe9, 0x0b, 0xfa, 0x5c, 0xb2, 0x7f, 0xd2, 0x2a, 0x78, 0xe9, 0x2d, 0xdf,
	0x7c, 0xf3, 0x9b, 0x2f, 0x33, 0x0b, 0x43, 0x45, 0x4a, 0x35, 0xa2, 0x2d, 0x3a, 0x29, 0xb4, 0xc0,
	0x74, 0xc5, 0x15, 0x6d, 0xb8, 0xa6, 0xf1, 0x77, 0x04, 0xe0, 0xbd, 0xf2, 0xa3, 0xc3, 0x4b, 0x08,
	0xcb, 0x39, 0x0b, 0x46, 0xc1, 0x24, 0x5b, 0x84, 0xe5, 0x1c, 0x19, 0x24, 0xaf, 0xa4, 0xbf, 0x84,
	0xdc, 0xb2, 0xd0, 0x16, 0x7b, 0x89, 0x37, 0x10, 0xbf, 0x29, 0x92, 0x65, 0xcd, 0x22, 0x6b, 0x78,
	0x85, 0xb7, 0x90, 0x55, 0x7e, 0x5e, 0xcd, 0xce, 0xac, 0x75, 0x2c, 0x60, 0x0e, 0x69, 0x45, 0x72,
	0x67, 0xb9, 0x81, 0x35, 0x0f, 0xda, 0x64, 0x2d, 0x25, 0x5f, 0x53, 0x59, 0xb3, 0xd8, 0x65, 0x79,
	0x69, 0xb2, 0xaa, 0x8e, 0x9b, 0x81, 0x89, 0xcb, 0x72, 0x0a, 0x9f, 0xcc, 0x34, 0xad, 0x9b, 0x76,
	0xa3, 0x58, 0x3a, 0x8a, 0x26, 0xe7, 0xf7, 0xe3, 0xa2, 0xdf, 0xac, 0x38, 0x6e, 0x55, 0xf4, 0x4d,
	0x2f, 0xad, 0x96, 0xfb, 0xc5, 0x81, 0xc1, 0x19, 0x24, 0xcf, 0x5c, 0xca, 0x86, 0x24, 0xcb, 0x2c,
	0x7e, 0xf7, 0x2f, 0xee, 0x7b, 0x1c, 0xdd, 0x13, 0x78, 0x0d, 0x83, 0xa5, 0xe8, 0x9a, 0x35, 0x03,
	0xfb, 0x4f, 0x4e, 0xe4, 0x33, 0x18, 0xfe, 0x49, 0xc3, 0x2b, 0x88, 0xb6, 0xb4, 0xf7, 0x27, 0x35,
	0x9f, 0x06, 0xdc, 0xf1, 0xf7, 0x4f, 0xf2, 0x17, 0x75, 0x62, 0x1a, 0x3e, 0x06, 0xf9, 0x14, 0x2e,
	0x7e, 0x67, 0x9d, 0xc2, 0xae, 0x62, 0xfb, 0xb2, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41,
	0x48, 0x6d, 0x73, 0xea, 0x01, 0x00, 0x00,
}
