// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: mqant_rpc.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      string   `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Fn       string   `protobuf:"bytes,2,opt,name=Fn,proto3" json:"Fn,omitempty"`
	ReplyTo  string   `protobuf:"bytes,3,opt,name=ReplyTo,proto3" json:"ReplyTo,omitempty"`
	Track    string   `protobuf:"bytes,4,opt,name=track,proto3" json:"track,omitempty"`
	Expired  int64    `protobuf:"varint,5,opt,name=Expired,proto3" json:"Expired,omitempty"`
	Reply    bool     `protobuf:"varint,6,opt,name=Reply,proto3" json:"Reply,omitempty"`
	ArgsType []string `protobuf:"bytes,7,rep,name=ArgsType,proto3" json:"ArgsType,omitempty"`
	Args     [][]byte `protobuf:"bytes,8,rep,name=Args,proto3" json:"Args,omitempty"`
	Caller   string   `protobuf:"bytes,9,opt,name=caller,proto3" json:"caller,omitempty"`
	Hostname string   `protobuf:"bytes,10,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *RPCInfo) Reset() {
	*x = RPCInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqant_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCInfo) ProtoMessage() {}

func (x *RPCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mqant_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCInfo.ProtoReflect.Descriptor instead.
func (*RPCInfo) Descriptor() ([]byte, []int) {
	return file_mqant_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCInfo) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *RPCInfo) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *RPCInfo) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *RPCInfo) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *RPCInfo) GetExpired() int64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *RPCInfo) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

func (x *RPCInfo) GetArgsType() []string {
	if x != nil {
		return x.ArgsType
	}
	return nil
}

func (x *RPCInfo) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RPCInfo) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *RPCInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ResultInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid        string `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Error      string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	ResultType string `protobuf:"bytes,4,opt,name=ResultType,proto3" json:"ResultType,omitempty"`
	Result     []byte `protobuf:"bytes,5,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ResultInfo) Reset() {
	*x = ResultInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqant_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultInfo) ProtoMessage() {}

func (x *ResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mqant_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultInfo.ProtoReflect.Descriptor instead.
func (*ResultInfo) Descriptor() ([]byte, []int) {
	return file_mqant_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ResultInfo) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ResultInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResultInfo) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *ResultInfo) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_mqant_rpc_proto protoreflect.FileDescriptor

var file_mqant_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x71, 0x61, 0x6e, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x72, 0x70, 0x63, 0x70, 0x62, 0x22, 0xef, 0x01, 0x0a, 0x07, 0x52, 0x50, 0x43,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x43, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x46, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x72, 0x67, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x41, 0x72, 0x67, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x6c, 0x0a, 0x0a, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x67, 0x64, 0x61, 0x73, 0x2f,
	0x6d, 0x71, 0x61, 0x6e, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqant_rpc_proto_rawDescOnce sync.Once
	file_mqant_rpc_proto_rawDescData = file_mqant_rpc_proto_rawDesc
)

func file_mqant_rpc_proto_rawDescGZIP() []byte {
	file_mqant_rpc_proto_rawDescOnce.Do(func() {
		file_mqant_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqant_rpc_proto_rawDescData)
	})
	return file_mqant_rpc_proto_rawDescData
}

var file_mqant_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mqant_rpc_proto_goTypes = []interface{}{
	(*RPCInfo)(nil),    // 0: rpcpb.RPCInfo
	(*ResultInfo)(nil), // 1: rpcpb.ResultInfo
}
var file_mqant_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mqant_rpc_proto_init() }
func file_mqant_rpc_proto_init() {
	if File_mqant_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqant_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqant_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqant_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mqant_rpc_proto_goTypes,
		DependencyIndexes: file_mqant_rpc_proto_depIdxs,
		MessageInfos:      file_mqant_rpc_proto_msgTypes,
	}.Build()
	File_mqant_rpc_proto = out.File
	file_mqant_rpc_proto_rawDesc = nil
	file_mqant_rpc_proto_goTypes = nil
	file_mqant_rpc_proto_depIdxs = nil
}
